name: foo
on: 
  push:
    branches:
        - main

jobs:

    echo_name:
        runs-on: ubuntu-latest
        steps:
            - name: Echo
              run: echo Shervin
    date:
        runs-on: ubuntu-latest
        steps:
            - name: Date
              run: date          